/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TemplateId = IDL.Text;
export const SocialHandleId = IDL.Text;
export const SocialHandle = IDL.Record({
  'id' : SocialHandleId,
  'url' : IDL.Text,
  'username' : IDL.Text,
  'platform' : IDL.Text,
});
export const LinkId = IDL.Text;
export const Link = IDL.Record({
  'id' : LinkId,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const TemplateStatus = IDL.Variant({
  'published' : IDL.Null,
  'unlisted' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const UserId = IDL.Principal;
export const Category = IDL.Text;
export const Template = IDL.Record({
  'id' : TemplateId,
  'status' : TemplateStatus,
  'thumbnail' : ExternalBlob,
  'editableContent' : IDL.Vec(IDL.Nat8),
  'name' : IDL.Text,
  'createdAt' : Time,
  'creatorId' : IDL.Opt(UserId),
  'description' : IDL.Text,
  'category' : Category,
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'premium' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'subscription' : IDL.Opt(SubscriptionTier),
  'userId' : UserId,
  'subscriptionExpiry' : IDL.Opt(Time),
  'email' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const ShareId = IDL.Text;
export const BioPage = IDL.Record({
  'bioText' : IDL.Text,
  'title' : IDL.Text,
  'templateId' : TemplateId,
  'userId' : UserId,
  'createdAt' : Time,
  'links' : IDL.Vec(Link),
  'updatedAt' : Time,
  'socialHandles' : IDL.Vec(SocialHandle),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBioPage' : IDL.Func(
      [TemplateId, IDL.Text, IDL.Text, IDL.Vec(SocialHandle), IDL.Vec(Link)],
      [],
      [],
    ),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFamousInfluencers' : IDL.Func(
      [Category],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getSharedBio' : IDL.Func([ShareId], [IDL.Opt(BioPage)], ['query']),
  'getTemplatesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Template)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasActiveSubscription' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'registerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFamousInfluencer' : IDL.Func([Category, UserProfile], [], []),
  'subscribe' : IDL.Func([SubscriptionTier, Time], [], []),
  'uploadTemplate' : IDL.Func(
      [IDL.Text, Category, IDL.Text, ExternalBlob, IDL.Vec(IDL.Nat8)],
      [TemplateId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TemplateId = IDL.Text;
  const SocialHandleId = IDL.Text;
  const SocialHandle = IDL.Record({
    'id' : SocialHandleId,
    'url' : IDL.Text,
    'username' : IDL.Text,
    'platform' : IDL.Text,
  });
  const LinkId = IDL.Text;
  const Link = IDL.Record({
    'id' : LinkId,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const TemplateStatus = IDL.Variant({
    'published' : IDL.Null,
    'unlisted' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const UserId = IDL.Principal;
  const Category = IDL.Text;
  const Template = IDL.Record({
    'id' : TemplateId,
    'status' : TemplateStatus,
    'thumbnail' : ExternalBlob,
    'editableContent' : IDL.Vec(IDL.Nat8),
    'name' : IDL.Text,
    'createdAt' : Time,
    'creatorId' : IDL.Opt(UserId),
    'description' : IDL.Text,
    'category' : Category,
  });
  const SubscriptionTier = IDL.Variant({
    'pro' : IDL.Null,
    'premium' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'subscription' : IDL.Opt(SubscriptionTier),
    'userId' : UserId,
    'subscriptionExpiry' : IDL.Opt(Time),
    'email' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const ShareId = IDL.Text;
  const BioPage = IDL.Record({
    'bioText' : IDL.Text,
    'title' : IDL.Text,
    'templateId' : TemplateId,
    'userId' : UserId,
    'createdAt' : Time,
    'links' : IDL.Vec(Link),
    'updatedAt' : Time,
    'socialHandles' : IDL.Vec(SocialHandle),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBioPage' : IDL.Func(
        [TemplateId, IDL.Text, IDL.Text, IDL.Vec(SocialHandle), IDL.Vec(Link)],
        [],
        [],
      ),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFamousInfluencers' : IDL.Func(
        [Category],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getSharedBio' : IDL.Func([ShareId], [IDL.Opt(BioPage)], ['query']),
    'getTemplatesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Template)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasActiveSubscription' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'registerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFamousInfluencer' : IDL.Func([Category, UserProfile], [], []),
    'subscribe' : IDL.Func([SubscriptionTier, Time], [], []),
    'uploadTemplate' : IDL.Func(
        [IDL.Text, Category, IDL.Text, ExternalBlob, IDL.Vec(IDL.Nat8)],
        [TemplateId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };