/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BioPage {
  'bioText' : string,
  'title' : string,
  'templateId' : TemplateId,
  'userId' : UserId,
  'createdAt' : Time,
  'links' : Array<Link>,
  'updatedAt' : Time,
  'socialHandles' : Array<SocialHandle>,
}
export type Category = string;
export type ExternalBlob = Uint8Array;
export interface Link {
  'id' : LinkId,
  'url' : string,
  'title' : string,
  'description' : string,
}
export type LinkId = string;
export type ShareId = string;
export interface SocialHandle {
  'id' : SocialHandleId,
  'url' : string,
  'username' : string,
  'platform' : string,
}
export type SocialHandleId = string;
export type SubscriptionTier = { 'pro' : null } |
  { 'premium' : null };
export interface Template {
  'id' : TemplateId,
  'status' : TemplateStatus,
  'thumbnail' : ExternalBlob,
  'editableContent' : Uint8Array,
  'name' : string,
  'createdAt' : Time,
  'creatorId' : [] | [UserId],
  'description' : string,
  'category' : Category,
}
export type TemplateId = string;
export type TemplateStatus = { 'published' : null } |
  { 'unlisted' : null };
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'subscription' : [] | [SubscriptionTier],
  'userId' : UserId,
  'subscriptionExpiry' : [] | [Time],
  'email' : string,
  'phoneNumber' : string,
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBioPage' : ActorMethod<
    [TemplateId, string, string, Array<SocialHandle>, Array<Link>],
    undefined
  >,
  'getAllTemplates' : ActorMethod<[], Array<Template>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFamousInfluencers' : ActorMethod<[Category], Array<UserProfile>>,
  'getSharedBio' : ActorMethod<[ShareId], [] | [BioPage]>,
  'getTemplatesByCategory' : ActorMethod<[Category], Array<Template>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasActiveSubscription' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'registerProfile' : ActorMethod<[string, string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFamousInfluencer' : ActorMethod<[Category, UserProfile], undefined>,
  'subscribe' : ActorMethod<[SubscriptionTier, Time], undefined>,
  'uploadTemplate' : ActorMethod<
    [string, Category, string, ExternalBlob, Uint8Array],
    TemplateId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];